name: Test workflow
on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  perform:
    runs-on: ubunutu-latest
    steps:
      - name: Hello world!
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"